### PR TITLE
WIP: Use Logging module instead of print for logging info

### PR DESCRIPTION
**Pull request by csfreak**
- [x] Dont use print for logging or errors
- [x] Dont write anything to stdout except output
- [x] Update existing tests to capture logs rather than stdout/stderr

### CODE REVIEW

**Comment by csfreak** [comment]
Will rebase after #15 is merged.  currently based on that branch to include changes to config module

**Comment by stratus-ss** [comment]
I say we push that through and have debug logs as its own thing when we get there

**Comment by stratus-ss** [comment]
@csfreak would it make sense in this PR to have the missing column error identify which header is missing? I want to add this for easier debugging from the user but it may make sense to do this in another PR.

Thoughts?

**Review by stratus-ss — APPROVED** [review]
LGTM pending above question

**Comment by csfreak** [comment]
> @csfreak would it make sense in this PR to have the missing column error identify which header is missing? I want to add this for easier debugging from the user but it may make sense to do this in another PR.
> 
> Thoughts?

The current logic doesn't make this information available, so I would argue that we shouldn't include it here.  To do that we would need to decide which version matched best,  and then report what's missing,  currently,  we just iterate through the options,  and if one matches, we continue, if we get to the end with no matches then we log the error.  At that point,  we dont know exactly what did and didn't match.

**Pull request merged**
